export interface BlockVariant {
  id: string;
  name: string;
  description: string;
  tags: string[];
  imageUrl?: string;
  library?: 'Untitled UI' | 'Tailgrids' | 'Horizon UI' | 'Built-in';
}

export interface BlockCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
}

export const BLOCK_CATEGORIES: BlockCategory[] = [
  { id: 'Text', name: 'Text & Article', icon: 'Type', description: 'Headings, paragraphs & quote blocks' },
  { id: 'Navigation', name: 'Header Menus', icon: 'Layout', description: 'Premium navbar designs' },
  { id: 'Hero', name: 'Hero Sections', icon: 'Sparkles', description: 'Premium header templates' },
  { id: 'Features', name: 'Feature Sections', icon: 'Grid', description: 'Showcase grids & bento boxes' },
  { id: 'CTA', name: 'Call to Actions', icon: 'Award', description: 'High-conversion CTA banners' },
  { id: 'Gallery', name: 'Gallery & Media', icon: 'Compass', description: 'Visual masonry grids & carousels' },
  { id: 'Business', name: 'Business Services', icon: 'Briefcase', description: 'Menus, treatments & packages' },
  { id: 'Pricing', name: 'Pricing Tiers', icon: 'DollarSign', description: 'SaaS & local service plans' },
  { id: 'Testimonials', name: 'Social Proof', icon: 'ThumbsUp', description: 'Wall of love & reviews' },
  { id: 'Forms', name: 'Lead Forms', icon: 'Mail', description: 'Booking & contact forms' },
  { id: 'EComStore', name: 'E-Commerce Storefront', icon: 'ShoppingBag', description: 'Product grid with direct gateway checkout' },
  { id: 'Map', name: 'Map & Location', icon: 'MapPin', description: 'Google Maps interactive embeds' },
  { id: 'Special', name: 'Special Widgets', icon: 'PlusCircle', description: 'FAQs, timelines & step guides' },
  { id: 'Footer', name: 'Footer Zones', icon: 'Layers', description: 'Brand directory layouts' }
];

export const BLOCK_VARIANTS_MAP: Record<string, BlockVariant[]> = {
  Text: [
    { id: 'signature-editorial', name: 'Signature Editorial Story', description: 'Oversized editorial typography, numbered annotation, and premium long-form reading rhythm', tags: ['Signature', 'Premium', 'Editorial', 'Story'], library: 'Built-in' },
    { id: 'article-body', name: 'Rich Article Paragraph', description: 'Clean readable text block with custom subheaders and leading', tags: ['Article', 'Paragraph', 'Minimal'], library: 'Built-in' },
    { id: 'quote-callout', name: 'Editorial Quote Callout', description: 'Highlighted quote box with accent border and author subtext', tags: ['Quote', 'Callout', 'Editorial'], library: 'Built-in' },
    { id: 'heading-minimal', name: 'Centered Heading & Subtext', description: 'Standalone headline with subtext and alignment controls', tags: ['Heading', 'Text', 'Clean'], library: 'Built-in' },
  ],
  Hero: [
    { id: 'local-conversion', name: 'Local Conversion', description: 'Action-first direction for calls, WhatsApp enquiries, and appointment bookings', tags: ['Local', 'WhatsApp', 'Conversion'] },
    { id: 'quiet-luxury', name: 'Quiet Luxury', description: 'Warm neutral palette, restrained accents, and high-end service positioning', tags: ['Luxury', 'Neutral', 'Elegant'] },
    { id: 'bold-poster', name: 'Bold Poster', description: 'Oversized display type and sharp contrast for energetic launches', tags: ['Bold', 'Launch', 'Display'] },
    { id: 'soft-gradient', name: 'Soft Gradient', description: 'Airy pastel gradients with calm spacing and approachable calls to action', tags: ['Gradient', 'Soft', 'Modern'] },
    { id: 'mono-grid', name: 'Monochrome Grid', description: 'Structured black-and-white visual system with precise editorial rhythm', tags: ['Mono', 'Grid', 'Swiss'] },
    { id: 'warm-studio', name: 'Warm Studio', description: 'Earthy colors and rounded shapes for human, craft-led businesses', tags: ['Warm', 'Organic', 'Friendly'] },
    { id: 'glass-panel', name: 'Glass Panel', description: 'Layered translucent surfaces with subtle borders and atmospheric depth', tags: ['Glass', 'Layered', 'Tech'] },
    { id: 'uiverse-hero-glow', name: 'Ambient Glass Hero', description: 'Ambient gradient orbs, frosted glass chips, and a glowing gradient CTA', tags: ['Glass', 'Gradient', 'Hero'], library: 'Built-in' },
    { id: 'mui-hero', name: 'Material Elevation Hero', description: 'Light hero with an elevated surface mock, stat strip, and contained buttons', tags: ['Elevation', 'Surface', 'Hero'], library: 'Built-in' }
  ],
  Features: [
    { id: 'signature-bento', name: 'Signature Capability Bento', description: 'Cohesive Signature-system bento cards with imagery, outcomes, and linked actions', tags: ['Signature', 'Premium', 'Bento', 'Media'] },
    { id: 'premium-bento-grid', name: 'Premium Outcome Bento', description: 'Art-directed asymmetric feature cards with imagery, outcome copy, and connected actions', tags: ['Premium', 'Bento', 'Interactive', 'Media'] },
    { id: 'untitled-feature-grid', name: 'Untitled UI Feature Grid', description: 'Clean 6-card feature matrix with icons and subtle hover scaling', tags: ['Untitled UI', 'Tailwind', 'Grid', 'Icons'], library: 'Untitled UI' },
    { id: 'tailgrids-feature-grid', name: 'Tailgrids Capability Grid', description: 'Modern 3-column feature cards with badges and hover glow', tags: ['Tailgrids', 'Feature', 'Capabilities'], library: 'Tailgrids' },
    { id: 'signature-bento', name: 'Signature Capability Bento', description: 'Cohesive Signature-system bento cards with imagery, outcomes, and linked actions', tags: ['Signature', 'Premium', 'Bento', 'Media'], library: 'Built-in' },
    { id: 'premium-bento-grid', name: 'Premium Outcome Bento', description: 'Art-directed asymmetric feature cards with imagery, outcome copy, and connected actions', tags: ['Premium', 'Bento', 'Interactive', 'Media'], library: 'Built-in' },
    { id: 'academy-courses', name: 'Editorial Course Grid', description: 'Image-led two-column curriculum cards with strong hierarchy and art-directed overlays', tags: ['Academy', 'Courses', 'Editorial', 'Media'], library: 'Built-in' },
    { id: 'feature-grid', name: 'Classic Icon Grid', description: 'Fully responsive grid layout with custom hover scale effects', tags: ['Grid', 'Modern', 'Symmetric'], library: 'Built-in' },
    { id: 'bento-box', name: 'Premium Bento Grid', description: 'Asymmetric grid layout inspired by Apple and Vercel', tags: ['Bento', 'Premium', 'Minimalist'], library: 'Built-in' },
    { id: 'uiverse-feature-grid', name: 'Frosted Glass Features', description: 'Frosted glass cards with gradient icon tiles and hover glow', tags: ['Glass', 'Features'], library: 'Built-in' },
    { id: 'mui-feature-grid', name: 'Material Surface Features', description: 'Six Material surface cards with tinted icon avatars and elevation hover', tags: ['Material', 'Features'], library: 'Built-in' },
  ],
  CTA: [
    { id: 'tailgrids-cta-banner', name: 'Tailgrids Gradient CTA', description: 'High-conversion newsletter CTA banner with email input and backdrop blur', tags: ['Tailgrids', 'CTA', 'Gradient', 'Newsletter'], library: 'Tailgrids' },
    { id: 'signature-cta', name: 'Signature Conversion Stage', description: 'Large restrained conversion moment with premium depth and a focused next action', tags: ['Signature', 'Premium', 'CTA', 'Conversion'], library: 'Built-in' },
    { id: 'simple-cta', name: 'Minimal Conversion Panel', description: 'High-contrast banner directing focus to a primary CTA', tags: ['Minimal', 'Fast'], library: 'Built-in' },
    { id: 'gradient-cta', name: 'High-Contrast Gradient Block', description: 'Glow-tinted canvas displaying high-energy newsletter setups', tags: ['Gradient', 'Modern', 'Immersive'], library: 'Built-in' },
    { id: 'uiverse-cta', name: 'Frosted Glass CTA', description: 'Translucent frosted panel with gradient border and pulsing glow', tags: ['Glass', 'CTA'], library: 'Built-in' },
    { id: 'mui-cta', name: 'Material Colour Band CTA', description: 'Primary color band with decorative circles and white contained CTA', tags: ['Material', 'CTA'], library: 'Built-in' },
    { id: 'untitled-cta', name: 'Untitled UI Dark CTA', description: 'Near-black centered conversion stage with feature chip and dual CTAs', tags: ['Untitled UI', 'Dark', 'CTA'], library: 'Untitled UI' },
  ],
  Gallery: [
    { id: 'horizon-nft-card', name: 'Horizon NFT & Media Card', description: 'Modern dark NFT showcase card with live bid status and media preview', tags: ['Horizon UI', 'NFT', 'Media', 'Card'], library: 'Horizon UI' },
    { id: 'signature-gallery', name: 'Signature Visual Archive', description: 'Cohesive Signature-system gallery with editorial mosaic and fullscreen lightbox', tags: ['Signature', 'Premium', 'Gallery', 'Lightbox'], library: 'Built-in' },
    { id: 'masonry', name: 'Staggered Masonry Grid', description: 'Pinterest-style fluid layouts resizing columns gracefully', tags: ['Artistic', 'Masonry', 'Media'], library: 'Built-in' },
  ],
  Business: [
    { id: 'horizon-metric-card', name: 'Horizon Dashboard Metrics', description: 'Clean admin stat card with growth badges, icon boxes, and subtitles', tags: ['Horizon UI', 'Metrics', 'Stats', 'Admin'], library: 'Horizon UI' },
    { id: 'untitled-stat-cards', name: 'Untitled UI Stat Cards', description: 'Minimalist stat cards with positive/negative growth badges', tags: ['Untitled UI', 'Stats', 'Badges'], library: 'Untitled UI' },
    { id: 'treatment-list', name: 'Luxury Treatment Menu', description: 'Fine-detailed lists displaying treatments, times, and costs', tags: ['Salon', 'Luxury', 'Treatments'], library: 'Built-in' },
    { id: 'packages', name: 'Service Packages Bento', description: 'Pre-bundled bundles featuring tick lists and accents', tags: ['Packages', 'Bespoke', 'Doctor'], library: 'Built-in' },
    { id: 'horizon-profile-card', name: 'Horizon Profile Card', description: 'Dark gradient-cover team profile with stats and quick actions', tags: ['Horizon UI', 'Profile', 'Team'], library: 'Horizon UI' },
  ],
  Pricing: [
    { id: 'untitled-pricing-tiers', name: 'Untitled UI Pricing Matrix', description: 'Structured 3-tier pricing table with recommended badges and feature checklists', tags: ['Untitled UI', 'Pricing', 'Checklist'], library: 'Untitled UI' },
    { id: 'tailgrids-pricing-table', name: 'Tailgrids Pricing Switcher', description: '3-Tier pricing table with interactive monthly/yearly billing toggle', tags: ['Tailgrids', 'Pricing', 'Toggle'], library: 'Tailgrids' },
    { id: 'signature-pricing', name: 'Signature Pricing System', description: 'Cohesive Signature-system plan comparison with working billing control', tags: ['Signature', 'Premium', 'Pricing', 'Interactive'], library: 'Built-in' },
    { id: 'saas-pricing', name: 'Standard SaaS 3-Tiers', description: 'Standard billing tiers highlighting a recommended choice', tags: ['SaaS', 'Tiers', 'Checklist'], library: 'Built-in' },
    { id: 'uiverse-pricing', name: 'Frosted Glass Pricing', description: 'Glass tiers with gradient popular plan and glowing checkmarks', tags: ['Glass', 'Pricing'], library: 'Built-in' },
    { id: 'mui-pricing', name: 'Material Elevation Pricing', description: 'Three Material tiers with a dark elevated recommended plan', tags: ['Material', 'Pricing'], library: 'Built-in' },
  ],
  Testimonials: [
    { id: 'signature-stories', name: 'Signature Customer Story', description: 'Cohesive Signature-system testimonial carousel with focused story presentation', tags: ['Signature', 'Premium', 'Stories', 'Carousel'] },
    { id: 'premium-testimonial-carousel', name: 'Premium Story Carousel', description: 'Large focused customer story with working previous/next controls, avatars, and ratings', tags: ['Premium', 'Carousel', 'Stories', 'Interactive'] },
    { id: 'academy-stories', name: 'Academy Student Stories', description: 'Dark editorial testimonial grid with understated proof and participant details', tags: ['Academy', 'Students', 'Editorial', 'Trust'] },
    { id: 'review-cards', name: 'Classic Review Tiles', description: 'Polished client statement blocks with dynamic star ratings', tags: ['Clean', 'Grid'] },
    { id: 'google-review', name: 'Google Stars & Badging', description: 'Trust-focused layout integrating Google Maps badges', tags: ['Google', 'Trust', 'Local-SEO'] },
    { id: 'wall-of-love', name: 'Masonry Wall of Love', description: 'A massive visual array of community appreciation letters', tags: ['WallOfLove', 'Premium'] },
    { id: 'editorial-stack', name: 'Editorial Customer Stories', description: 'Long-form, human testimonials with a polished publication feel', tags: ['Editorial', 'Stories', 'Premium'] },
    { id: 'local-conversion', name: 'Local Trust Stories', description: 'Trust-focused review direction for neighbourhood businesses', tags: ['Local', 'Trust', 'Conversion'] },
    { id: 'quiet-luxury', name: 'Private Client Notes', description: 'Understated testimonials for premium and confidential services', tags: ['Luxury', 'Elegant', 'Service'] },
    { id: 'soft-gradient', name: 'Friendly Review Cloud', description: 'Warm approachable reviews with soft color and rounded surfaces', tags: ['Soft', 'Reviews', 'Friendly'] },
    { id: 'mono-grid', name: 'Case Study Quotes', description: 'Crisp testimonial system for agencies, studios, and B2B teams', tags: ['Mono', 'Case Study', 'B2B'] },
    { id: 'uiverse-testimonials', name: 'Frosted Glass Reviews', description: 'Frosted glass review cards with gradient avatars and star ratings', tags: ['Glass', 'Reviews'], library: 'Built-in' },
    { id: 'mui-testimonials', name: 'Material Surface Reviews', description: 'Material review cards with tinted initial avatars and elevation', tags: ['Material', 'Reviews'], library: 'Built-in' },
    { id: 'untitled-testimonials', name: 'Untitled UI Testimonial Grid', description: 'Clean bordered review cards with indigo initial avatars', tags: ['Untitled UI', 'Reviews'], library: 'Untitled UI' },
    { id: 'tailgrids-testimonials', name: 'Tailgrids Review Cards', description: 'Soft-shadowed testimonial tiles with quote watermark and blue avatars', tags: ['Tailgrids', 'Reviews'], library: 'Tailgrids' }
  ],
  Forms: [
    { id: 'signature-form', name: 'Signature Lead Workspace', description: 'Cohesive Signature-system form with configurable fields, contact channels, and lead routing', tags: ['Signature', 'Premium', 'Lead', 'Configurable'] },
    { id: 'premium-contact-panel', name: 'Premium Contact Workspace', description: 'Configurable lead form paired with direct contact channels and a real submission workflow', tags: ['Premium', 'Lead', 'Contact', 'Configurable'] },
    { id: 'academy-enquiry', name: 'Academy Course Enquiry', description: 'Premium configurable enquiry form for course interests, dates, and learning goals', tags: ['Academy', 'Lead', 'Configurable'] },
    { id: 'academy-registration', name: 'Course Registration', description: 'Structured enrollment form with course selection, batch date, payment, and notes', tags: ['Academy', 'Enrollment', 'Registration'] },
    { id: 'academy-portal', name: 'Student Portal Access', description: 'Focused sign-in and access-request panel for members and enrolled students', tags: ['Academy', 'Portal', 'Authentication'] },
    { id: 'appointment', name: 'Lead Form & Booking', description: 'Fully styled reservation boxes capturing names, emails, and slots', tags: ['Interactive', 'Forms', 'Booking'] },
    { id: 'newsletter', name: 'High-Impact Subscriber Bar', description: 'One-click newsletter subscriptions with custom validations', tags: ['Subscribers', 'Bar'] },
    { id: 'contact-complex', name: 'Detailed Contact Grid', description: 'Direct contact form flanked by interactive maps and contact details', tags: ['Forms', 'Detailed', 'Contact'] },
    { id: 'local-conversion', name: 'WhatsApp Lead Form', description: 'Compact enquiry flow designed to continue the conversation on WhatsApp', tags: ['WhatsApp', 'Lead', 'Local'] },
    { id: 'quiet-luxury', name: 'Private Consultation Form', description: 'Refined intake experience for premium appointments and enquiries', tags: ['Luxury', 'Consultation', 'Form'] },
    { id: 'bold-poster', name: 'Campaign Signup Form', description: 'High-energy lead capture for launches, events, and limited offers', tags: ['Bold', 'Campaign', 'Lead'] },
    { id: 'soft-gradient', name: 'Friendly Enquiry Form', description: 'Approachable rounded form styling that reduces visual friction', tags: ['Soft', 'Friendly', 'Form'] },
    { id: 'mono-grid', name: 'Professional Brief Form', description: 'Structured intake for agencies, consultants, and B2B services', tags: ['Mono', 'Brief', 'Professional'] },
    { id: 'uiverse-lead-form', name: 'Frosted Glass Lead Form', description: 'Frosted glass capture card with gradient focus rings and glow button', tags: ['Glass', 'Lead'], library: 'Built-in' },
    { id: 'mui-lead-form', name: 'Material Outlined Lead Form', description: 'Material outlined fields with focused ring states and contained submit', tags: ['Material', 'Lead'], library: 'Built-in' }
  ],
  EComStore: [
    { id: 'signature-store', name: 'Signature Product Edit', description: 'Premium editorial product shelf with featured storytelling, live pricing, stock, and connected checkout actions', tags: ['Signature', 'Premium', 'Store', 'Commerce'] },
    { id: 'single-product-hero', name: 'Single Product Landing Buy Card', description: 'Hero product showcase card with instant Buy Now button for single-item landing pages', tags: ['LandingPage', 'SingleProduct', 'BuyNow'] },
    { id: 'shop-header', name: 'Shopify Style Header & Announcement', description: 'Top announcement bar + brand logo + shop links + search & cart pill', tags: ['Header', 'Shopify', 'Nav'] },
    { id: 'product-grid-filter', name: 'Untitled UI Filterable Product Catalog', description: 'Category pills, tag filters, price range, sorting & SEO alt tags', tags: ['Catalog', 'UntitledUI', 'Shop'] },
    { id: 'offer-gallery', name: 'Featured Offers & Flash Sales Gallery', description: 'Shows products tagged OnSale/Featured with offer badges & countdown', tags: ['Offers', 'Sales', 'Badges'] },
    { id: 'interactive-feature', name: 'Interactive React Feature Canvas', description: 'Mouse-follow card glow, image tilt, reveal animations & marquee', tags: ['FramerMotion', 'MouseGlow', 'Interactive'] },
    { id: 'whatsapp-widget', name: 'Floating WhatsApp Store Button', description: 'Direct WhatsApp action button linking to merchant phone number', tags: ['WhatsApp', 'Floating', 'Automated'] },
    { id: 'customer-auth', name: 'Storefront Customer Login & Signup', description: 'Shopify Canvas Light / Cream customer sign-in & registration template', tags: ['Auth', 'Login', 'Signup'] },
    { id: 'store-legal', name: 'Store Terms & Refund Policies', description: 'Terms of Service, Shipping, and Privacy Policy page layout', tags: ['Legal', 'Terms', 'Compliance'] },
    { id: 'local-conversion', name: 'WhatsApp Commerce Shelf', description: 'Local storefront direction built around chat-to-buy and UPI intent', tags: ['WhatsApp', 'UPI', 'Local'] },
    { id: 'quiet-luxury', name: 'Luxury Product Edit', description: 'Restrained high-end product presentation for boutique brands', tags: ['Luxury', 'Boutique', 'Product'] },
    { id: 'bold-poster', name: 'Drop Launch Store', description: 'Bold campaign treatment for new drops and limited inventory', tags: ['Launch', 'Drop', 'Bold'] },
    { id: 'warm-studio', name: 'Maker Market', description: 'Warm organic storefront direction for handmade and independent brands', tags: ['Maker', 'Warm', 'Organic'] }
  ],
  Special: [
    { id: 'signature-faq', name: 'Signature Information Accordion', description: 'Cohesive Signature-system supporting content with accessible interactive questions', tags: ['Signature', 'Premium', 'FAQ', 'Interactive'] },
    { id: 'premium-proof-rail', name: 'Premium Trust Rail', description: 'Compact high-credibility strip for key numbers, assurances, certifications, or brand proof', tags: ['Premium', 'Trust', 'Metrics', 'Compact'] },
    { id: 'premium-results-metrics', name: 'Premium Results Stage', description: 'Oversized performance numbers with editorial hierarchy and responsive data cards', tags: ['Premium', 'Results', 'Metrics', 'Editorial'] },
    { id: 'premium-roadmap', name: 'Premium Journey Roadmap', description: 'Responsive numbered journey with connected milestones and clear supporting explanations', tags: ['Premium', 'Roadmap', 'Process', 'Timeline'] },
    { id: 'premium-faq', name: 'Premium FAQ Accordion', description: 'Editorial FAQ layout with working accessible expand and collapse interactions', tags: ['Premium', 'FAQ', 'Accordion', 'Interactive'] },
    { id: 'academy-process', name: 'Academy Numbered Process', description: 'Large editorial step numbers with structured education workflow copy', tags: ['Academy', 'Process', 'Editorial'] },
    { id: 'faq-accordions', name: 'FAQ Interactive Drawers', description: 'Interactive accordion list maximizing space gracefully', tags: ['Accordions', 'Interactive'] },
    { id: 'steps-path', name: 'Step Process Roadmap', description: 'Horizontal paths mapping the user journey', tags: ['Timeline', 'Roadmap'] },
    { id: 'stats-grid', name: 'Performance Counters Grid', description: 'Animated numeric metrics describing growth accomplishments', tags: ['Numbers', 'Counters'] },
    { id: 'editorial-stack', name: 'Editorial Information Stack', description: 'Typography-led supporting content with refined visual pacing', tags: ['Editorial', 'Content', 'Premium'] },
    { id: 'local-conversion', name: 'Local Action Utility', description: 'Practical conversion support for calls, enquiries, and directions', tags: ['Local', 'Action', 'Utility'] },
    { id: 'quiet-luxury', name: 'Luxury Detail Panel', description: 'Understated supporting content for premium brand stories', tags: ['Luxury', 'Detail', 'Elegant'] },
    { id: 'mono-grid', name: 'Monochrome Data Panel', description: 'Structured facts and process content with strong information hierarchy', tags: ['Mono', 'Data', 'Grid'] },
    { id: 'glass-panel', name: 'Glass Utility Panel', description: 'Atmospheric layered surface for technology and product details', tags: ['Glass', 'Tech', 'Utility'] },
    { id: 'uiverse-stat-grid', name: 'Frosted Glass Stats', description: 'Frosted stat cards with gradient numbers and divider chips', tags: ['Glass', 'Stats'], library: 'Built-in' },
    { id: 'tailgrids-logo-cloud', name: 'Tailgrids Logo Cloud', description: 'Six-box trust strip for brand logos and social proof', tags: ['Tailgrids', 'Logos', 'Trust'], library: 'Tailgrids' },
    { id: 'horizon-data-table', name: 'Horizon Data Table', description: 'Dark admin check table with status pills and trend amounts', tags: ['Horizon UI', 'Table', 'Admin'], library: 'Horizon UI' }
  ],
  Navigation: [
    { id: 'nav-signature', name: '00. Signature Editorial Header', description: 'Cohesive Signature-system header with responsive navigation and dual conversion paths', tags: ['Signature', 'Premium', 'Responsive'] },
    { id: 'nav-academy', name: '01. Cinematic Academy Header', description: 'Transparent editorial navigation with dual conversion actions and responsive menu', tags: ['Academy', 'Transparent', 'Premium'] },
    { id: 'nav-minimal', name: '01. Minimal Left Brand', description: 'Simple brand text, centered clean links, and a solid outline action button.', tags: ['Minimal', 'Light'] },
    { id: 'nav-glass', name: '02. Frosted Floating Glass', description: 'Elegant glassmorphic panel floating centrally with a subtle blur effect.', tags: ['Glassmorphism', 'Premium'] },
    { id: 'nav-centered-logo', name: '03. Symmetric Centered Brand', description: 'Centered brand text with evenly split navigation links on left & right sides.', tags: ['Symmetric', 'Elegant'] },
    { id: 'nav-sidebar-toggle', name: '04. Sidebar Drawer Switch', description: 'Extremely clean header that toggles a rich full-page overlay drawer.', tags: ['Drawer', 'Minimal'] },
    { id: 'nav-mega-menu', name: '05. Interactive SaaS Mega-Menu', description: 'Enterprise header with beautiful hovering grid dropdowns for complex links.', tags: ['SaaS', 'Dropdown'] },
    { id: 'nav-search-bar', name: '06. Integrated Search Box', description: 'Embedded interactive search bar in center with customer dashboard indicators.', tags: ['Interactive', 'Input'] },
    { id: 'nav-social-icons', name: '07. Social Links Left', description: 'Features active social icons on the left margins, main links on the right.', tags: ['Social', 'Compact'] },
    { id: 'nav-double-header', name: '08. Double-Deck Announcement', description: 'Top colored discount banner paired with a primary structural menu.', tags: ['Utility', 'Banner'] },
    { id: 'nav-retro-mono', name: '09. Brutalist Wireframe Mono', description: 'Monospaced fonts, solid thick black borders, and stark high-contrast squares.', tags: ['Brutalist', 'Mono'] },
    { id: 'nav-pill-shaped', name: '10. Compact Capsule Pill', description: 'Tiny horizontal pill floating at the very top with micro action triggers.', tags: ['Capsule', 'Creative'] },
    { id: 'nav-blur-reveal', name: '11. Scroll Blur Reveal', description: 'Invisible at hero peak, transitions into a frosted glass banner upon scroll.', tags: ['Scroll', 'UX'] },
    { id: 'nav-with-avatar', name: '12. Active Profile Portal', description: 'Built-in workspace avatar dropdown with direct status flags.', tags: ['Portal', 'Dashboard'] },
    { id: 'nav-dark-neon', name: '13. Dark Neon Aura', description: 'Glowing active indicators styled with deep violet and gold outlines.', tags: ['Dark', 'Neon'] },
    { id: 'nav-badge-alert', name: '14. Promotional Badge Highlight', description: 'Displays an animated hot-sale promo badge next to the primary action.', tags: ['Sales', 'Badge'] },
    { id: 'nav-burger-only', name: '15. Minimal Hamburg Overlay', description: 'Just three lines that spring-rotate on hover, revealing a modal panel.', tags: ['Minimal', 'Drawer'] },
    { id: 'nav-with-phone', name: '16. Hotline Quick-Dial', description: 'Displays a large, clickable telephone hotline button on the header.', tags: ['Contact', 'Service'] },
    { id: 'nav-gradient-border', name: '17. Shifting Accent Underline', description: 'Active links trigger an animated shifting gradient bar underneath.', tags: ['Creative', 'Underline'] },
    { id: 'nav-language-picker', name: '18. Language Globe Switcher', description: 'Built-in international globe dropdown showing regional languages.', tags: ['Globe', 'Global'] },
    { id: 'nav-ecommerce-cart', name: '19. Shopping Cart Indicator', description: 'Displays a live shopping cart count bubble next to account buttons.', tags: ['Store', 'Cart'] },
    { id: 'nav-command-k', name: '20. Spotlight Cmd+K Input', description: 'A gorgeous faux command-K input bar for triggering global lookups.', tags: ['Search', 'Shortcut'] },
    { id: 'nav-glowing-glow', name: '21. Futuristic Cyber Rail', description: 'Glowing cyan neon strip with a modern cybertech font styling.', tags: ['Futuristic', 'Cyber'] }
  ],
  Footer: [
    { id: 'footer-signature', name: '00. Signature Brand Footer', description: 'Cohesive Signature-system footer with story, navigation, contact, social, and risk or legal note', tags: ['Signature', 'Premium', 'Editorial'] },
    { id: 'footer-academy', name: '01. Academy Editorial Footer', description: 'Clean light footer with brand story, page links, contact details, and legal navigation', tags: ['Academy', 'Editorial', 'Contact'] },
    { id: 'footer-classic', name: '01. Corporate 4-Column Index', description: 'Robust directory footer featuring logo, copy, newsletter form, and structured grids.', tags: ['Directory', 'Corporate'] },
    { id: 'footer-minimal', name: '02. Centered Single-Row Ribbon', description: 'Slim horizontal ribbon centering copyright labels and tiny circle social pills.', tags: ['Minimal', 'Clean'] },
    { id: 'footer-brand-huge', name: '03. Ultra-Display Huge Branding', description: 'Gigantic typographic branding headline stacked on top of 3 dense content lists.', tags: ['Display', 'Bold'] },
    { id: 'footer-retro-wire', name: '04. Brutalist Thick Outline', description: 'Heavy solid borders, monospaced text columns, and strict black block styling.', tags: ['Brutalist', 'Mono'] },
    { id: 'footer-newsletter-focus', name: '05. High-Impact Subscription Focus', description: 'Displays a massive, beautiful centered email newsletter box with standard links below.', tags: ['Newsletter', 'Capture'] },
    { id: 'footer-social-wall', name: '06. Grid Social Wall Preview', description: 'Features a beautiful grid of mockup visual squares with direct social clickables.', tags: ['Social', 'Grid'] },
    { id: 'footer-compact-badge', name: '07. Trust Badges & Certifications', description: 'Compact dual-row footer showcasing security trust badges and certifications.', tags: ['Trust', 'Security'] },
    { id: 'footer-three-col-cta', name: '08. Integrated Mini-CTA Block', description: 'Features a beautiful gradient call-to-action banner sitting directly on top of links.', tags: ['CTA', 'Modern'] },
    { id: 'footer-dark-cosmos', name: '09. Radial Spotlight Dark Cosmos', description: 'Stunning dark background with a soft ambient radial light glowing behind the links.', tags: ['Dark', 'Cosmic'] },
    { id: 'footer-accordion', name: '10. Mobile-Optimized Accordion', description: 'Interactive collapsing list panels that organize columns cleanly on smaller layouts.', tags: ['Mobile', 'Collapsible'] },
    { id: 'footer-split-legal', name: '11. Split Legal & Cookie Toggles', description: 'Separate blocks for Privacy, Terms, Cookies settings, and a mock server-status indicator.', tags: ['Legal', 'Utility'] },
    { id: 'footer-with-map', name: '12. Location Blueprint Map', description: 'Embedded mock location map canvas on the left, with full address columns on the right.', tags: ['Contact', 'Maps'] },
    { id: 'footer-bento-footer', name: '13. Premium Bento Grid Columns', description: 'Asymmetrical structural blocks of various sizes hosting social, newsletter, and links.', tags: ['Bento', 'Premium'] },
    { id: 'footer-multilingual', name: '14. Multi-Locale Select Dropdown', description: 'Full footer containing a language dropdown flag selector beside standard copyright.', tags: ['International', 'SaaS'] },
    { id: 'footer-quick-booking', name: '15. Quick Appointment Booking', description: 'Direct booking schedule selector input field built straight into the footer block.', tags: ['Interactive', 'Booking'] },
    { id: 'footer-trustpilot-rating', name: '16. External Trustpilot Star Panel', description: 'Integrates real-looking star ratings and testimonial score badge indicators.', tags: ['Trust', 'Review'] },
    { id: 'footer-with-backtotop', name: '17. Built-in Back-to-Top Anchor', description: 'Displays an elegant scrolling chevron button to sweep visitors back to the peak.', tags: ['Navigation', 'UX'] },
    { id: 'footer-gradient-glow', name: '18. Shifting Horizon Gradient', description: 'Features an elegant moving neon horizon line separating the footer from the canvas.', tags: ['Gradient', 'Futuristic'] },
    { id: 'footer-jobs-hiring', name: '19. Active Careers Hiring Flag', description: 'Displays a glowing green pulsing "We are Hiring!" dot next to company links.', tags: ['Careers', 'Badge'] },
    { id: 'footer-copyright-only', name: '21. Super-Minimal Copyright Rail', description: 'Single elegant thin line containing copyright text and absolutely nothing else.', tags: ['Minimalist'] },
    { id: 'mui-footer', name: 'Dark Elevated Footer', description: 'Dark four-column footer with logo, social pills, and legal rail', tags: ['Material', 'Footer'], library: 'Built-in' },
    { id: 'untitled-footer', name: 'Untitled UI Footer', description: 'Light five-column footer with tagline, link columns, and social icons', tags: ['Untitled UI', 'Footer'], library: 'Untitled UI' },
    { id: 'tailgrids-footer', name: 'Tailgrids Navy Footer', description: 'Navy four-column footer with newsletter-feel link groups and socials', tags: ['Tailgrids', 'Footer'], library: 'Tailgrids' }
  ],
  Map: [
    { id: 'signature-map', name: 'Signature Location Canvas', description: 'Premium location module with editorial address details, direct actions, and an interactive map', tags: ['Signature', 'Premium', 'Map', 'Contact'] },
    { id: 'map-classic', name: 'Interactive Location Map', description: 'Fully custom Google Map of your business location', tags: ['Location', 'Interactive', 'Google Maps'] },
    { id: 'local-conversion', name: 'Visit & Contact', description: 'Location details paired with direct call, directions, and WhatsApp actions', tags: ['Local', 'Directions', 'WhatsApp'] },
    { id: 'quiet-luxury', name: 'Destination Address', description: 'Refined location presentation for hotels, clinics, and premium studios', tags: ['Luxury', 'Address', 'Elegant'] },
    { id: 'mono-grid', name: 'Location Directory', description: 'Structured monochrome address block for multi-location businesses', tags: ['Mono', 'Directory', 'Locations'] },
    { id: 'warm-studio', name: 'Neighbourhood Guide', description: 'Warm, welcoming location direction for hospitality and local services', tags: ['Warm', 'Local', 'Guide'] }
  ]
};

// ==========================================
// DYNAMIC INDUSTRY PRESET INITIALIZERS
// ==========================================

export const INDUSTRY_PRESETS: Record<string, { name: string; icon: string; description: string; blocks: any[] }> = {
  salon: {
    name: 'Luxury Beauty Salon',
    icon: 'Sparkles',
    description: 'Perfect for salons, spas, and wellness hubs with service menus and bookings.',
    blocks: [
      {
        type: 'Hero',
        variant: 'aurora-sky',
        badge: 'AMBIENT LUXURY WELLNESS',
        title: 'Rejuvenate Your Senses. Restore Your Glow.',
        subtitle: 'Experience world-class beauty treatments curated by expert aestheticians in Bengaluru’s premier relaxation sanctuary.',
        imageUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1200',
        btnText: 'Secure Your Slot',
        styles: {
          backgroundColor: '#0a0a0a',
          textColor: '#f5f5f5',
          subtitleColor: '#a3a3a3',
          accentColor: '#d4af37', // Gold
          badgeBgColor: '#1a1a1a',
          badgeTextColor: '#d4af37',
          buttonBgColor: '#d4af37',
          buttonTextColor: '#0a0a0a',
          fontFamily: 'Playfair Display',
          titleSize: 52,
          titleWeight: 'bold',
          subtitleSize: 18,
          bodySize: 14,
          paddingTop: 110,
          paddingBottom: 110,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 24,
          maxWidth: 1200,
          textAlign: 'center',
          useGradient: true,
          backgroundGradient: 'linear-gradient(135deg, #09090b 0%, #1c1917 100%)',
          cardBgColor: '#1c1917',
          cardTextColor: '#f5f5f5',
          cardBorderRadius: 12,
          cardShadow: 'lg',
          cardBorderWidth: 1,
          cardBorderColor: '#2e2a24',
          borderRadius: 0,
          borderWidth: 0,
          borderColor: '',
          borderStyle: 'solid',
          boxShadow: 'none',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      },
      {
        type: 'Business',
        variant: 'treatment-list',
        badge: 'TREATMENTS & MASSAGES',
        title: 'Premium Beauty Offerings',
        subtitle: 'Every appointment includes complimentary organic refreshments and therapeutic massage rituals.',
        features: [
          { id: 't-1', title: 'Signature Gold Radiance Facial', desc: '1 hr 15 mins • Deep exfoliation with real gold leaf treatments.', icon: 'Award' },
          { id: 't-2', title: 'Balinese Deep Tissue Massage', desc: '1 hr 30 mins • Restores cellular balance using pure warm oils.', icon: 'Heart' },
          { id: 't-3', title: 'Advanced Hydrafacial Infusion', desc: '45 mins • Dynamic peptide infusions with vacuum microdermabrasion.', icon: 'Check' }
        ],
        styles: {
          backgroundColor: '#121212',
          textColor: '#f5f5f5',
          subtitleColor: '#a3a3a3',
          accentColor: '#d4af37',
          badgeBgColor: '#1a1a1a',
          badgeTextColor: '#d4af37',
          fontFamily: 'Inter',
          titleSize: 36,
          titleWeight: 'semibold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 16,
          maxWidth: 1100,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#18181b',
          cardTextColor: '#f5f5f5',
          cardBorderRadius: 8,
          cardShadow: 'md',
          cardBorderWidth: 1,
          cardBorderColor: '#27272a',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      },
      {
        type: 'Forms',
        variant: 'appointment',
        badge: 'INSTANT RESERVATION',
        title: 'Book Your Treatment',
        subtitle: 'No pre-payment required. Secure your premium spa slot instantly online.',
        btnText: 'Confirm Booking',
        styles: {
          backgroundColor: '#0a0a0a',
          textColor: '#f5f5f5',
          subtitleColor: '#a3a3a3',
          accentColor: '#d4af37',
          badgeBgColor: '#1a1a1a',
          badgeTextColor: '#d4af37',
          buttonBgColor: '#d4af37',
          buttonTextColor: '#0a0a0a',
          fontFamily: 'Inter',
          titleSize: 36,
          titleWeight: 'semibold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 20,
          maxWidth: 900,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#18181b',
          cardTextColor: '#f5f5f5',
          cardBorderRadius: 12,
          cardShadow: 'xl',
          cardBorderWidth: 1,
          cardBorderColor: '#27272a',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      }
    ]
  },
  doctor: {
    name: 'Healthcare Specialist',
    icon: 'Briefcase',
    description: 'Clean medical clinics and independent practitioner profiles.',
    blocks: [
      {
        type: 'Hero',
        variant: 'split',
        badge: 'CLINICAL EXCELLENCE',
        title: 'Expert Medical Care For Your Whole Family',
        subtitle: 'Consult with board-certified healthcare professionals utilizing cutting-edge diagnostics in Koramangala’s primary multispecialty hospital.',
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=800',
        btnText: 'Book Consult',
        styles: {
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
          subtitleColor: '#475569',
          accentColor: '#0ea5e9', // Blue/Sky
          badgeBgColor: '#f0f9ff',
          badgeTextColor: '#0ea5e9',
          buttonBgColor: '#0ea5e9',
          buttonTextColor: '#ffffff',
          fontFamily: 'Inter',
          titleSize: 48,
          titleWeight: 'bold',
          subtitleSize: 16,
          bodySize: 14,
          paddingTop: 90,
          paddingBottom: 90,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 24,
          maxWidth: 1200,
          textAlign: 'left',
          useGradient: false,
          cardBgColor: '#f8fafc',
          cardTextColor: '#0f172a',
          cardBorderRadius: 12,
          cardShadow: 'md',
          cardBorderWidth: 1,
          cardBorderColor: '#e2e8f0',
          borderRadius: 0,
          borderWidth: 0,
          borderColor: '',
          borderStyle: 'solid',
          boxShadow: 'none',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      },
      {
        type: 'Features',
        variant: 'bento-box',
        badge: 'SPECIALTY DEPARTMENTS',
        title: 'Modern Clinical Services',
        subtitle: 'Covering complete pediatric, cardiac, orthopedic, and preventive wellness checks.',
        features: [
          { id: 'd-1', title: 'Preventive Screenings', desc: 'Full diagnostic reports within 4 hours using advanced lab technologies.', icon: 'Heart' },
          { id: 'd-2', title: 'Cardiology Services', desc: 'Electrocardiograms and expert consulting available 24/7 on call.', icon: 'Award' },
          { id: 'd-3', title: 'Telehealth Consults', desc: 'Speak to doctors remotely via high-definition video conferencing.', icon: 'Globe' }
        ],
        styles: {
          backgroundColor: '#f8fafc',
          textColor: '#0f172a',
          subtitleColor: '#475569',
          accentColor: '#0ea5e9',
          badgeBgColor: '#f0f9ff',
          badgeTextColor: '#0ea5e9',
          fontFamily: 'Inter',
          titleSize: 34,
          titleWeight: 'bold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 16,
          maxWidth: 1100,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#ffffff',
          cardTextColor: '#0f172a',
          cardBorderRadius: 16,
          cardShadow: 'lg',
          cardBorderWidth: 1,
          cardBorderColor: '#cbd5e1',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      },
      {
        type: 'Forms',
        variant: 'appointment',
        badge: 'SCHEDULE NOW',
        title: 'Book Your Clinical Appointment',
        subtitle: 'Our coordinators will confirm your exact consultation slot within 10 minutes.',
        btnText: 'Secure Appointment Slot',
        styles: {
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
          subtitleColor: '#475569',
          accentColor: '#0ea5e9',
          badgeBgColor: '#f0f9ff',
          badgeTextColor: '#0ea5e9',
          buttonBgColor: '#0ea5e9',
          buttonTextColor: '#ffffff',
          fontFamily: 'Inter',
          titleSize: 36,
          titleWeight: 'semibold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 85,
          paddingBottom: 85,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 20,
          maxWidth: 850,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#f8fafc',
          cardTextColor: '#0f172a',
          cardBorderRadius: 12,
          cardShadow: 'xl',
          cardBorderWidth: 1,
          cardBorderColor: '#cbd5e1',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      }
    ]
  },
  portfolio: {
    name: 'Tech Specialist / Creator',
    icon: 'Compass',
    description: 'Bespoke portfolio headers with 3D elements, marquee widgets, and work galleries.',
    blocks: [
      {
        type: 'Hero',
        variant: 'gradient-glow',
        badge: 'AVAILABLE FOR FREELANCE',
        title: 'Crafting High-Performance Interactive Products',
        subtitle: 'Independent Full Stack Engineer & Designer specializing in bespoke React systems, animation engines, and WebGL layouts.',
        imageUrl: '',
        btnText: 'View Client Works',
        styles: {
          backgroundColor: '#030712',
          textColor: '#f9fafb',
          subtitleColor: '#9ca3af',
          accentColor: '#a855f7', // Purple
          badgeBgColor: '#1e1b4b',
          badgeTextColor: '#c084fc',
          buttonBgColor: '#a855f7',
          buttonTextColor: '#ffffff',
          fontFamily: 'Space Grotesk',
          titleSize: 56,
          titleWeight: 'black',
          subtitleSize: 18,
          bodySize: 14,
          paddingTop: 120,
          paddingBottom: 120,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 24,
          maxWidth: 1000,
          textAlign: 'center',
          useGradient: true,
          backgroundGradient: 'linear-gradient(135deg, #090514 0%, #030712 100%)',
          cardBgColor: '#0b0f19',
          cardTextColor: '#f9fafb',
          cardBorderRadius: 16,
          cardShadow: '2xl',
          cardBorderWidth: 1,
          cardBorderColor: '#3b0764',
          borderRadius: 0,
          borderWidth: 0,
          borderColor: '',
          borderStyle: 'solid',
          boxShadow: 'none',
          buttonBorderRadius: 50,
          buttonHoverScale: true
        }
      },
      {
        type: 'Gallery',
        variant: 'grid-hover',
        badge: 'SELECTED RECENT PROJECTS',
        title: 'Proof of Craftsmanship',
        subtitle: 'A meticulous curation of digital assets designed from scratch.',
        features: [
          { id: 'p-1', title: 'Aura UI Framework', desc: 'Interactive component engine rendering shaders at 60fps.', icon: 'Sparkles' },
          { id: 'p-2', title: 'Metropolis CRM Hub', desc: 'Secure data management visualizer handling millions of items.', icon: 'Database' },
          { id: 'p-3', title: 'Helios Landing Builder', desc: 'Tailwind compilation pipeline outputting beautiful pages.', icon: 'Layout' }
        ],
        styles: {
          backgroundColor: '#090514',
          textColor: '#f9fafb',
          subtitleColor: '#9ca3af',
          accentColor: '#a855f7',
          badgeBgColor: '#1e1b4b',
          badgeTextColor: '#c084fc',
          fontFamily: 'JetBrains Mono',
          titleSize: 32,
          titleWeight: 'bold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 16,
          maxWidth: 1200,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#120b24',
          cardTextColor: '#f9fafb',
          cardBorderRadius: 12,
          cardShadow: 'lg',
          cardBorderWidth: 1,
          cardBorderColor: '#2e1065',
          buttonBorderRadius: 8,
          buttonHoverScale: true
        }
      },
      {
        type: 'Forms',
        variant: 'contact-complex',
        badge: 'SECURE COLAB CONVERSATION',
        title: 'Start a High-Fidelity Project',
        subtitle: 'Fill out the details to review timelines, assets, and hourly project rates.',
        btnText: 'Initiate Request',
        contactEmail: 'create@helix-labs.io',
        contactPhone: '+1 (555) 019-2834',
        contactAddress: 'San Francisco, CA',
        styles: {
          backgroundColor: '#030712',
          textColor: '#f9fafb',
          subtitleColor: '#9ca3af',
          accentColor: '#a855f7',
          badgeBgColor: '#1e1b4b',
          badgeTextColor: '#c084fc',
          buttonBgColor: '#a855f7',
          buttonTextColor: '#ffffff',
          fontFamily: 'Inter',
          titleSize: 36,
          titleWeight: 'semibold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 20,
          maxWidth: 1000,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#0c101d',
          cardTextColor: '#f9fafb',
          cardBorderRadius: 16,
          cardShadow: '2xl',
          cardBorderWidth: 1,
          cardBorderColor: '#1e293b',
          buttonBorderRadius: 12,
          buttonHoverScale: true
        }
      }
    ]
  },
  realestate: {
    name: 'Real Estate Elite',
    icon: 'Grid',
    description: 'Display luxury properties, listings grids, maps, and lead captures.',
    blocks: [
      {
        type: 'Hero',
        variant: 'split',
        badge: 'PRESTIGIOUS LIVING',
        title: 'Discover Luxury Residencies Tailored To You',
        subtitle: 'Unlock premium gated properties, bespoke high-rises, and private villas in Bengaluru’s finest luxury residential zones.',
        imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
        btnText: 'View Listings',
        styles: {
          backgroundColor: '#0f172a',
          textColor: '#f8fafc',
          subtitleColor: '#cbd5e1',
          accentColor: '#10b981', // Emerald
          badgeBgColor: '#064e3b',
          badgeTextColor: '#10b981',
          buttonBgColor: '#10b981',
          buttonTextColor: '#ffffff',
          fontFamily: 'Inter',
          titleSize: 46,
          titleWeight: 'bold',
          subtitleSize: 16,
          bodySize: 14,
          paddingTop: 100,
          paddingBottom: 100,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 24,
          maxWidth: 1200,
          textAlign: 'left',
          useGradient: false,
          cardBgColor: '#1e293b',
          cardTextColor: '#f8fafc',
          cardBorderRadius: 8,
          cardShadow: 'md',
          cardBorderWidth: 1,
          cardBorderColor: '#334155',
          borderRadius: 0,
          borderWidth: 0,
          borderColor: '',
          borderStyle: 'solid',
          boxShadow: 'none',
          buttonBorderRadius: 4,
          buttonHoverScale: true
        }
      },
      {
        type: 'Features',
        variant: 'feature-grid',
        badge: 'PRESTIGE ADVANTAGES',
        title: 'Why Real Estate Elite?',
        subtitle: 'Securing legal titles, low brokerage overheads, and immediate site consultation bookings.',
        features: [
          { id: 're-1', title: '100% Verified Titles', desc: 'Complete transparent documentation and direct legal support.', icon: 'Check' },
          { id: 're-2', title: 'Zero Brokerage Gimmick', desc: 'Save over ₹2,00,000 on purchase overheads directly.', icon: 'Award' },
          { id: 're-3', title: 'Instant Site Transport', desc: 'Complimentary chauffeured transport for properties visual checks.', icon: 'MapPin' }
        ],
        styles: {
          backgroundColor: '#ffffff',
          textColor: '#0f172a',
          subtitleColor: '#475569',
          accentColor: '#10b981',
          badgeBgColor: '#d1fae5',
          badgeTextColor: '#065f46',
          fontFamily: 'Inter',
          titleSize: 34,
          titleWeight: 'bold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 80,
          paddingBottom: 80,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 16,
          maxWidth: 1100,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#f8fafc',
          cardTextColor: '#0f172a',
          cardBorderRadius: 8,
          cardShadow: 'md',
          cardBorderWidth: 1,
          cardBorderColor: '#e2e8f0',
          buttonBorderRadius: 4,
          buttonHoverScale: true
        }
      },
      {
        type: 'Forms',
        variant: 'newsletter',
        badge: 'WEEKLY PREMIUM REPORT',
        title: 'Subscribe For Elite Off-Market Properties',
        subtitle: 'Get curated real-estate insights sent directly to your inbox every Thursday morning.',
        btnText: 'Subscribe Now',
        styles: {
          backgroundColor: '#10b981',
          textColor: '#ffffff',
          subtitleColor: '#d1fae5',
          accentColor: '#ffffff',
          badgeBgColor: '#065f46',
          badgeTextColor: '#ffffff',
          buttonBgColor: '#0f172a',
          buttonTextColor: '#ffffff',
          fontFamily: 'Inter',
          titleSize: 32,
          titleWeight: 'bold',
          subtitleSize: 15,
          bodySize: 13,
          paddingTop: 70,
          paddingBottom: 70,
          paddingLeft: 24,
          paddingRight: 24,
          gapSize: 20,
          maxWidth: 1000,
          textAlign: 'center',
          useGradient: false,
          cardBgColor: '#ffffff',
          cardTextColor: '#0f172a',
          cardBorderRadius: 8,
          cardShadow: 'lg',
          cardBorderWidth: 1,
          cardBorderColor: '#e2e8f0',
          buttonBorderRadius: 4,
          buttonHoverScale: true
        }
      }
    ]
  }
};
